// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// The Prisma CLI (migrate, db push, studio) reads the datasource URL from
// here. `import "dotenv/config"` above loads it from the git-ignored `.env`
// file (see `.env.example`). The app runtime gets the URL via the pg driver
// adapter in lib/prisma.ts instead.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
