-- Step 19.2: rename the external-wallet payment method and add the internal
-- HezalliPay balance method. RENAME VALUE preserves existing rows (a DROP+ADD
-- would fail against data), so this is hand-written rather than autogenerated.

-- AlterEnum: WALLET (external local wallet) -> LOCAL_WALLET
ALTER TYPE "PaymentMethod" RENAME VALUE 'WALLET' TO 'LOCAL_WALLET';

-- AlterEnum: add the internal wallet payment method
ALTER TYPE "PaymentMethod" ADD VALUE 'HEZALLI_BALANCE';
